# 1. Kết nối MS SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CuoiKyElechain;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Cấu hình Hibernate 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cloudinary Config Template
cloudinary.cloud-name=tfso12it
cloudinary.api-key=YOUR_KEY_HERE
cloudinary.api-secret=YOUR_SECRET_HERE

# Khai báo cho Spring biết cần đọc thêm file secret
spring.profiles.include=secret